"use client";
import {useEffect,useState} from "react";

export default function Home(){
 const [me,setMe]=useState(null),[tab,setTab]=useState("dashboard"),[rows,setRows]=useState([]),[msg,setMsg]=useState(""),[copied,setCopied]=useState("");
 const [inspectors,setInspectors]=useState([]),[offices,setOffices]=useState([]);
 const [userForm,setUserForm]=useState({name:"",email:"",password:"",office_id:""});
 const [form,setForm]=useState({inspection_date:new Date().toISOString().slice(0,10),reason:"Inspeção",plan_no:"",order_no:"",location:"",equipment_no:"",operation:"",suboperation:"",description:""});

 const load=async()=>{let m=await fetch("/api/me");if(m.ok){let j=await m.json();setMe(j.user);let r=await fetch("/api/inspections");if(r.ok)setRows(await r.json())}};
 const loadUsers=async()=>{let r=await fetch("/api/users");if(r.ok){let j=await r.json();setInspectors(j.inspectors||[]);setOffices(j.offices||[]);setUserForm(f=>({...f,office_id:f.office_id||String(j.offices?.[0]?.id||"")}))}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(me?.role==="PCM")loadUsers()},[me]);

 async function login(e){e.preventDefault();let fd=new FormData(e.currentTarget);let r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});if(!r.ok){setMsg("Credenciais inválidas");return}setMsg("");await load()}
 async function save(e){e.preventDefault();let r=await fetch("/api/inspections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});let j=await r.json();if(!r.ok){setMsg(j.error);return}setMsg("Registro salvo no banco de dados.");setForm({...form,plan_no:"",order_no:"",location:"",equipment_no:"",operation:"",suboperation:"",description:""});await load();setTab("history")}
 async function edit(r){let d=prompt("Editar descrição:",r.description);if(d===null||d===r.description)return;let x=await fetch("/api/inspections",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id,description:d})});if(x.ok){setMsg("Descrição atualizada com rastreabilidade.");await load()}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setMe(null);setInspectors([]);setMsg("")}
 async function createInspector(e){e.preventDefault();let r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...userForm,office_id:Number(userForm.office_id)})});let j=await r.json();if(!r.ok){setMsg(j.error||"Não foi possível cadastrar o inspetor.");return}setMsg("Inspetor cadastrado com sucesso.");setUserForm({name:"",email:"",password:"",office_id:String(offices[0]?.id||"")});await loadUsers()}
 async function resetPassword(u){let p=prompt(`Nova senha para ${u.name}:`);if(p===null)return;if(p.length<8){setMsg("A senha deve ter pelo menos 8 caracteres.");return}let r=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,action:"password",password:p})});let j=await r.json();setMsg(r.ok?"Senha alterada com sucesso.":j.error||"Erro ao alterar senha.")}
 async function toggleInspector(u){let r=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,action:"active",active:!u.active})});let j=await r.json();if(!r.ok){setMsg(j.error||"Erro ao atualizar usuário.");return}setMsg(u.active?"Inspetor desativado.":"Inspetor reativado.");await loadUsers()}

 if(!me)return <div className="login"><form className="loginCard" onSubmit={login}><div style={{color:"#db1016",fontWeight:900,fontSize:12}}>GEM • GESTÃO ESTRATÉGICA DE MANUTENÇÃO</div><h1 style={{marginTop:8}}>GEM Inspeções</h1><p>Aplicação em nuvem com banco de dados próprio.</p>{msg&&<div className="status">{msg}</div>}<div className="field"><label>E-MAIL</label><input name="email" defaultValue="inspetor@gem.local"/></div><div className="field"><label>SENHA</label><input name="password" type="password" defaultValue="GEM@2026"/></div><button className="btn primary" style={{width:"100%"}}>Entrar</button></form></div>;
 const inspector=me.role==="INSPECTOR";
 return <><header className="top"><div className="brand">GEM | Inspeções</div><div style={{fontSize:12}}>{me.name} • {inspector?"Inspetor":"PCM"}</div></header><div className="wrap">
 <div className="tabs"><button className="btn secondary" onClick={()=>setTab("dashboard")}>Dashboard</button>{inspector&&<button className="btn secondary" onClick={()=>setTab("new")}>Nova inspeção</button>}<button className="btn secondary" onClick={()=>setTab("history")}>Histórico</button>{!inspector&&<button className="btn secondary" onClick={()=>{setTab("users");loadUsers()}}>Inspetores</button>}<a className="btn secondary" href="/api/export" style={{textDecoration:"none"}}>Exportar Excel</a><button className="btn secondary" onClick={logout}>Sair</button></div>
 {msg&&<div className="status">{msg}</div>}
 {tab==="dashboard"&&<><h1>Dashboard de Inspeções</h1><p>{inspector?"Visão da oficina vinculada ao seu usuário.":"Visão consolidada para análise do PCM."}</p><div className="grid4"><div className="metric"><small>REGISTROS</small><strong>{rows.length}</strong></div><div className="metric"><small>INSPEÇÕES</small><strong>{rows.filter(x=>x.reason==="Inspeção").length}</strong></div><div className="metric"><small>REVISÕES</small><strong>{rows.filter(x=>x.reason==="Revisão de Plano").length}</strong></div><div className="metric"><small>EQUIPAMENTOS</small><strong>{new Set(rows.map(x=>x.equipment_no)).size}</strong></div></div></>}
 {tab==="new"&&inspector&&<div className="panel"><h2>Nova Inspeção</h2><p>Oficina vinculada ao usuário: <b>{me.office_id?"definida pelo cadastro":"—"}</b></p><form onSubmit={save}><div className="formgrid">
 {["reason","plan_no","order_no","inspection_date","location","equipment_no","operation","suboperation"].map(k=><div className="field" key={k}><label>{({reason:"MOTIVO",plan_no:"Nº PLANO",order_no:"Nº ORDEM",inspection_date:"DATA",location:"LOCAL / LINHA",equipment_no:"Nº EQUIPAMENTO",operation:"OPERAÇÃO",suboperation:"SUB-OPERAÇÃO"})[k]}</label>{k==="reason"?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}><option>Inspeção</option><option>Revisão de Plano</option></select>:<input required={["inspection_date","location","equipment_no","operation"].includes(k)} type={k==="inspection_date"?"date":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</div>)}
 <div className="field span2"><label>DESCRIÇÃO</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{copied&&<button type="button" className="btn secondary" style={{marginTop:7}} onClick={()=>setForm({...form,description:copied})}>Usar descrição copiada</button>}</div></div><div className="actions"><button className="btn primary">Salvar no banco</button></div></form></div>}
 {tab==="history"&&<div className="panel"><h2>Histórico</h2><div className="tablewrap"><table><thead><tr><th>DATA</th><th>OFICINA</th><th>EQUIPAMENTO</th><th>LOCAL</th><th>MOTIVO</th><th>DESCRIÇÃO</th><th>AÇÕES</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{String(r.inspection_date).slice(0,10)}</td><td>{r.office}</td><td>{r.equipment_no}</td><td>{r.location}</td><td>{r.reason}</td><td style={{minWidth:280}}>{r.description}</td><td><div className="descActions"><button className="btn secondary" onClick={()=>{navigator.clipboard?.writeText(r.description);setCopied(r.description);setMsg("Descrição copiada.")}}>Copiar</button><button className="btn secondary" onClick={()=>edit(r)}>Editar</button></div></td></tr>)}</tbody></table></div></div>}
 {tab==="users"&&!inspector&&<><div className="panel" style={{marginBottom:16}}><h2>Cadastro de Inspetores</h2><p>Crie o acesso do inspetor e vincule-o à oficina responsável. O inspetor visualizará apenas os registros da própria oficina.</p><form onSubmit={createInspector}><div className="formgrid"><div className="field"><label>NOME</label><input required value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/></div><div className="field"><label>E-MAIL</label><input required type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></div><div className="field"><label>SENHA INICIAL</label><input required minLength={8} type="password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></div><div className="field"><label>OFICINA</label><select required value={userForm.office_id} onChange={e=>setUserForm({...userForm,office_id:e.target.value})}>{offices.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div></div><div className="actions"><button className="btn primary">Cadastrar inspetor</button></div></form></div>
 <div className="panel"><h2>Inspetores cadastrados</h2><div className="tablewrap"><table><thead><tr><th>NOME</th><th>E-MAIL</th><th>OFICINA</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>{inspectors.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.office}</td><td>{u.active?"Ativo":"Inativo"}</td><td><div className="descActions"><button className="btn secondary" onClick={()=>resetPassword(u)}>Alterar senha</button><button className="btn secondary" onClick={()=>toggleInspector(u)}>{u.active?"Desativar":"Reativar"}</button></div></td></tr>)}</tbody></table></div></div></>}
 </div></>
}
