"use client";
import {useEffect,useState} from "react";

function parseDate(value){const s=String(value||"").slice(0,10);const [y,m,d]=s.split("-").map(Number);if(!y||!m||!d)return null;return new Date(Date.UTC(y,m-1,d))}
function isoDate(d){return d.toISOString().slice(0,10)}
function weekStart(d){const x=new Date(d);const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-(day-1));return x}
function periodKey(value,period){const d=parseDate(value);if(!d)return null;if(period==="day")return isoDate(d);if(period==="week")return isoDate(weekStart(d));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-01`}
function periodLabel(key,period){const d=parseDate(key);if(!d)return key;const dd=String(d.getUTCDate()).padStart(2,"0"),mm=String(d.getUTCMonth()+1).padStart(2,"0"),yy=d.getUTCFullYear();if(period==="day")return `${dd}/${mm}`;if(period==="week")return `Sem. ${dd}/${mm}`;return `${mm}/${yy}`}
function buildSeries(rows,period){const counts=new Map();for(const r of rows){const k=periodKey(r.inspection_date,period);if(k)counts.set(k,(counts.get(k)||0)+1)}const keys=[...counts.keys()].sort();if(!keys.length)return [];let cur=parseDate(keys[0]),end=parseDate(keys[keys.length-1]);const out=[];while(cur&&end&&cur<=end){const k=isoDate(cur);out.push({key:k,label:periodLabel(k,period),value:counts.get(k)||0});if(period==="day")cur.setUTCDate(cur.getUTCDate()+1);else if(period==="week")cur.setUTCDate(cur.getUTCDate()+7);else cur.setUTCMonth(cur.getUTCMonth()+1,1)}const limit=period==="day"?31:period==="week"?16:12;return out.slice(-limit)}
function TrendChart({data}){if(!data.length)return <div className="emptyChart">Ainda não há inspeções para o filtro selecionado.</div>;const width=980,height=270,left=48,right=22,top=18,bottom=46;const max=Math.max(1,...data.map(x=>x.value));const x=i=>data.length===1?(left+width-right)/2:left+i*((width-left-right)/(data.length-1));const y=v=>top+(max-v)*((height-top-bottom)/max);const points=data.map((p,i)=>`${x(i)},${y(p.value)}`).join(" ");const step=Math.max(1,Math.ceil(data.length/8));return <div className="trendWrap"><svg className="trendSvg" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolução de inspeções">{[0,.25,.5,.75,1].map((g,i)=>{const val=Math.round(max*(1-g));const gy=top+g*(height-top-bottom);return <g key={i}><line x1={left} x2={width-right} y1={gy} y2={gy} className="gridLine"/><text x={left-10} y={gy+4} textAnchor="end" className="axisText">{val}</text></g>})}<polyline points={points} className="trendLine" fill="none"/>{data.map((p,i)=><g key={p.key}><circle cx={x(i)} cy={y(p.value)} r="5" className="trendPoint"/><text x={x(i)} y={y(p.value)-11} textAnchor="middle" className="pointText">{p.value}</text>{(i%step===0||i===data.length-1)&&<text x={x(i)} y={height-18} textAnchor="middle" className="axisText">{p.label}</text>}</g>)}</svg></div>}

const emptyInspectionForm=()=>({inspection_date:new Date().toISOString().slice(0,10),reason:"Inspeção",plan_no:"",order_no:"",location:"",equipment_no:"",operation:"",description:"",needs_part:false,part_description:"",stock_status:"",part_code:"",suboperation_count:1,suboperations:[""]});

export default function Home(){
 const [me,setMe]=useState(null),[tab,setTab]=useState("dashboard"),[rows,setRows]=useState([]),[msg,setMsg]=useState(""),[copied,setCopied]=useState("");
 const [inspectors,setInspectors]=useState([]),[offices,setOffices]=useState([]);
 const [dashboardOffice,setDashboardOffice]=useState("ALL"),[dashboardPeriod,setDashboardPeriod]=useState("day");
 const [userForm,setUserForm]=useState({name:"",email:"",password:"",office_id:""});
 const [form,setForm]=useState(emptyInspectionForm());
 const load=async()=>{let m=await fetch("/api/me",{cache:"no-store"});if(m.ok){let j=await m.json();setMe(j.user);let r=await fetch("/api/inspections",{cache:"no-store"});if(r.ok)setRows(await r.json())}else setMe(null)};
 const loadUsers=async()=>{let r=await fetch("/api/users",{cache:"no-store"});if(r.ok){let j=await r.json();setInspectors(j.inspectors||[]);setOffices(j.offices||[]);setUserForm(f=>({...f,office_id:f.office_id||String(j.offices?.[0]?.id||"")}))}};
 useEffect(()=>{load()},[]);useEffect(()=>{if(me?.role==="PCM")loadUsers()},[me]);

 function changeReason(reason){setForm(f=>({...f,reason,operation:"",suboperation_count:1,suboperations:[""],needs_part:false,part_description:"",stock_status:"",part_code:""}))}
 function setSubCount(v){let n=Math.max(1,Math.min(50,Number(v)||1));setForm(f=>{let arr=[...f.suboperations];if(arr.length<n)arr=[...arr,...Array(n-arr.length).fill("")];else arr=arr.slice(0,n);return {...f,suboperation_count:n,suboperations:arr}})}
 function setSubDescription(i,v){setForm(f=>({...f,suboperations:f.suboperations.map((x,idx)=>idx===i?v:x)}))}
 async function login(e){e.preventDefault();let fd=new FormData(e.currentTarget);let r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});if(!r.ok){setMsg("Credenciais inválidas");return}setMsg("");await load()}
 async function save(e){e.preventDefault();let payload={...form};if(form.reason==="Inspeção"&&form.stock_status==="Sem cadastro")payload.part_code="";let r=await fetch("/api/inspections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let j=await r.json();if(!r.ok){setMsg(j.error);return}setMsg("Registro salvo no banco de dados.");setForm(emptyInspectionForm());await load();setTab("history")}
 async function edit(r){let d=prompt("Editar descrição:",r.description);if(d===null||d===r.description)return;let x=await fetch("/api/inspections",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id,description:d})});if(x.ok){setMsg("Descrição atualizada com rastreabilidade.");await load()}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setMe(null);setInspectors([]);setRows([]);setMsg("");setTab("dashboard")}
 async function createInspector(e){e.preventDefault();let r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...userForm,office_id:Number(userForm.office_id)})});let j=await r.json();if(!r.ok){setMsg(j.error||"Não foi possível cadastrar o inspetor.");return}setMsg("Inspetor cadastrado com sucesso.");setUserForm({name:"",email:"",password:"",office_id:String(offices[0]?.id||"")});await loadUsers()}
 async function resetPassword(u){let p=prompt(`Nova senha para ${u.name}:`);if(p===null)return;if(p.length<8){setMsg("A senha deve ter pelo menos 8 caracteres.");return}let r=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,action:"password",password:p})});let j=await r.json();setMsg(r.ok?"Senha alterada com sucesso.":j.error||"Erro ao alterar senha.")}
 async function toggleInspector(u){let r=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,action:"active",active:!u.active})});let j=await r.json();if(!r.ok){setMsg(j.error||"Erro ao atualizar usuário.");return}setMsg(u.active?"Inspetor desativado.":"Inspetor reativado.");await loadUsers()}
 async function deleteInspector(u){if(!window.confirm(`Confirma a exclusão do inspetor ${u.name}? Esta ação não poderá ser desfeita.`))return;let r=await fetch("/api/users",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id})});let j=await r.json();if(!r.ok){setMsg(j.error||"Não foi possível excluir o inspetor.");return}setMsg("Inspetor excluído com sucesso.");await loadUsers()}
 async function deleteInspection(r){if(!window.confirm(`Confirma a exclusão do registro do equipamento ${r.equipment_no}? Esta ação excluirá também o histórico de revisões deste registro e não poderá ser desfeita.`))return;let x=await fetch("/api/inspections",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id})});let j=await x.json();if(!x.ok){setMsg(j.error||"Não foi possível excluir o registro.");return}setMsg("Registro excluído com sucesso.");await load()}

 if(!me)return <div className="login"><form className="loginCard" onSubmit={login}><div style={{color:"#db1016",fontWeight:900,fontSize:12}}>GEM • GESTÃO ESTRATÉGICA DE MANUTENÇÃO</div><h1 style={{marginTop:8}}>GEM Inspeções</h1><p>Aplicação em nuvem com banco de dados próprio.</p>{msg&&<div className="status">{msg}</div>}<div className="field"><label>E-MAIL / USUÁRIO</label><input name="email" autoComplete="username"/></div><div className="field"><label>SENHA</label><input name="password" type="password" autoComplete="current-password"/></div><button className="btn primary" style={{width:"100%"}}>Entrar</button></form></div>;
 const inspector=me.role==="INSPECTOR";
 const officeNames=[...new Set(rows.map(r=>r.office).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));
 const dashboardRows=!inspector&&dashboardOffice!=="ALL"?rows.filter(r=>r.office===dashboardOffice):rows;
 const inspectionRows=dashboardRows.filter(x=>x.reason==="Inspeção");const trend=buildSeries(inspectionRows,dashboardPeriod);
 return <><header className="top"><div className="brand">GEM | Inspeções</div><div style={{fontSize:12}}>{me.name} • {inspector?"Inspetor":"PCM"}</div></header><div className="wrap">
 <div className="tabs"><button className="btn secondary" onClick={()=>setTab("dashboard")}>Dashboard</button>{inspector&&<button className="btn secondary" onClick={()=>setTab("new")}>Nova inspeção</button>}<button className="btn secondary" onClick={()=>setTab("history")}>Histórico</button>{!inspector&&<button className="btn secondary" onClick={()=>{setTab("users");loadUsers()}}>Inspetores</button>}<a className="btn secondary" href="/api/export" style={{textDecoration:"none"}}>Exportar Excel</a><button className="btn secondary" onClick={logout}>Sair</button></div>
 {msg&&<div className="status">{msg}</div>}
 {tab==="dashboard"&&<><div className="dashboardHead"><div><h1>Dashboard de Inspeções</h1><p>{inspector?"Visão da oficina vinculada ao seu usuário.":"Visão consolidada para análise do PCM."}</p></div>{!inspector&&<div className="officeFilter"><label>OFICINA</label><select value={dashboardOffice} onChange={e=>setDashboardOffice(e.target.value)}><option value="ALL">Todas as oficinas</option>{officeNames.map(o=><option key={o} value={o}>{o}</option>)}</select></div>}</div><div className="grid4"><div className="metric"><small>REGISTROS</small><strong>{dashboardRows.length}</strong></div><div className="metric"><small>INSPEÇÕES</small><strong>{inspectionRows.length}</strong></div><div className="metric"><small>REVISÕES</small><strong>{dashboardRows.filter(x=>x.reason==="Revisão de Plano").length}</strong></div><div className="metric"><small>EQUIPAMENTOS</small><strong>{new Set(dashboardRows.map(x=>x.equipment_no).filter(Boolean)).size}</strong></div></div>{!inspector&&<div className="panel trendPanel"><div className="trendHeader"><div><h2>Evolução de inspeções</h2><p>Quantidade de inspeções registradas no período selecionado.</p></div><div className="periodButtons"><button className={`btn ${dashboardPeriod==="day"?"primary":"secondary"}`} onClick={()=>setDashboardPeriod("day")}>Dia</button><button className={`btn ${dashboardPeriod==="week"?"primary":"secondary"}`} onClick={()=>setDashboardPeriod("week")}>Semana</button><button className={`btn ${dashboardPeriod==="month"?"primary":"secondary"}`} onClick={()=>setDashboardPeriod("month")}>Mês</button></div></div><TrendChart data={trend}/></div>}</>}
 {tab==="new"&&inspector&&<div className="panel"><h2>Nova Inspeção</h2><p>Oficina vinculada ao usuário: <b>{me.office_id?"definida pelo cadastro":"—"}</b></p><form onSubmit={save}><div className="formgrid">
 <div className="field"><label>MOTIVO</label><select value={form.reason} onChange={e=>changeReason(e.target.value)}><option>Inspeção</option><option>Revisão de Plano</option></select></div>
 <div className="field"><label>Nº PLANO</label><input value={form.plan_no} onChange={e=>setForm({...form,plan_no:e.target.value})}/></div>
 <div className="field"><label>Nº ORDEM</label><input value={form.order_no} onChange={e=>setForm({...form,order_no:e.target.value})}/></div>
 <div className="field"><label>DATA</label><input required type="date" value={form.inspection_date} onChange={e=>setForm({...form,inspection_date:e.target.value})}/></div>
 <div className="field"><label>LOCAL / LINHA</label><input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div>
 <div className="field"><label>Nº EQUIPAMENTO</label><input required value={form.equipment_no} onChange={e=>setForm({...form,equipment_no:e.target.value})}/></div>
 {form.reason==="Revisão de Plano"&&<>
   <div className="field"><label>OPERAÇÃO</label><input required value={form.operation} onChange={e=>setForm({...form,operation:e.target.value})}/></div>
   <div className="field"><label>QUANTIDADE DE SUB-OPERAÇÕES</label><input required min="1" max="50" type="number" value={form.suboperation_count} onChange={e=>setSubCount(e.target.value)}/></div>
   <div className="span2 subopsBox"><h3>Sub-operações</h3>{form.suboperations.map((s,i)=><div className="field" key={i}><label>SUB-OPERAÇÃO {i+1} — DESCRIÇÃO</label><input required value={s} onChange={e=>setSubDescription(i,e.target.value)} placeholder={`Descreva a sub-operação ${i+1}`}/></div>)}</div>
 </>}
 {form.reason==="Inspeção"&&<>
   <div className="field"><label>NECESSITA DE PEÇA?</label><select value={form.needs_part?"Sim":"Não"} onChange={e=>setForm({...form,needs_part:e.target.value==="Sim",part_description:e.target.value==="Sim"?form.part_description:"",stock_status:e.target.value==="Sim"?form.stock_status:"",part_code:e.target.value==="Sim"?form.part_code:""})}><option>Não</option><option>Sim</option></select></div>
   {form.needs_part&&<>
     <div className="field"><label>DESCRIÇÃO DA PEÇA</label><input required value={form.part_description} onChange={e=>setForm({...form,part_description:e.target.value})}/></div>
     <div className="field"><label>STATUS NO ALMOXERIFADO</label><select required value={form.stock_status} onChange={e=>setForm({...form,stock_status:e.target.value,part_code:e.target.value==="Sem cadastro"?"":form.part_code})}><option value="">Selecione</option><option>Possui</option><option>Não possui</option><option>Sem cadastro</option></select></div>
     {form.stock_status!=="Sem cadastro"&&<div className="field"><label>CÓDIGO DA PEÇA</label><input required value={form.part_code} onChange={e=>setForm({...form,part_code:e.target.value})}/></div>}
   </>}
 </>}
 <div className="field span2"><label>DESCRIÇÃO</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{copied&&<button type="button" className="btn secondary" style={{marginTop:7}} onClick={()=>setForm({...form,description:copied})}>Usar descrição copiada</button>}</div>
 </div><div className="actions"><button className="btn primary">Salvar no banco</button></div></form></div>}
 {tab==="history"&&<div className="panel"><h2>Histórico</h2><div className="tablewrap"><table><thead><tr><th>DATA</th><th>OFICINA</th><th>EQUIPAMENTO</th><th>LOCAL</th><th>MOTIVO</th><th>DESCRIÇÃO</th><th>AÇÕES</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{String(r.inspection_date).slice(0,10)}</td><td>{r.office}</td><td>{r.equipment_no}</td><td>{r.location}</td><td>{r.reason}</td><td style={{minWidth:280}}>{r.description}</td><td><div className="descActions"><button className="btn secondary" onClick={()=>{navigator.clipboard?.writeText(r.description);setCopied(r.description);setMsg("Descrição copiada.")}}>Copiar</button><button className="btn secondary" onClick={()=>edit(r)}>Editar</button>{!inspector&&<button className="btn danger" onClick={()=>deleteInspection(r)}>Excluir</button>}</div></td></tr>)}</tbody></table></div></div>}
 {tab==="users"&&!inspector&&<><div className="panel" style={{marginBottom:16}}><h2>Cadastro de Inspetores</h2><p>Crie o acesso do inspetor e vincule-o à oficina responsável. O inspetor visualizará apenas os registros da própria oficina.</p><form onSubmit={createInspector}><div className="formgrid"><div className="field"><label>NOME</label><input required value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/></div><div className="field"><label>E-MAIL / USUÁRIO</label><input required type="text" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})} placeholder="ex.: marcelo@inspetor"/></div><div className="field"><label>SENHA INICIAL</label><input required minLength={8} type="password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></div><div className="field"><label>OFICINA</label><select required value={userForm.office_id} onChange={e=>setUserForm({...userForm,office_id:e.target.value})}>{offices.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div></div><div className="actions"><button className="btn primary">Cadastrar inspetor</button></div></form></div><div className="panel"><h2>Inspetores cadastrados</h2><div className="tablewrap"><table><thead><tr><th>NOME</th><th>E-MAIL / USUÁRIO</th><th>OFICINA</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>{inspectors.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.office}</td><td>{u.active?"Ativo":"Inativo"}</td><td><div className="descActions"><button className="btn secondary" onClick={()=>resetPassword(u)}>Alterar senha</button><button className="btn secondary" onClick={()=>toggleInspector(u)}>{u.active?"Desativar":"Reativar"}</button><button className="btn danger" onClick={()=>deleteInspector(u)}>Excluir</button></div></td></tr>)}</tbody></table></div></div></>}
 </div></>
}
